ts = int(input("Tiempo en segundos: "))
H = int(ts / 3600)
RH = int(ts % 3600)
M = int(RH / 60)
RM = int(RH % 60)
print("")
print("Horas: " + str(H))
print("Minutos: " + str(M))
print("Segundos: " + str(RM))
