mm = int(input("Distancia en milímetros: "))
m = int(mm / 1000)
RM = int(mm % 1000)
dm = int(RM / 100)
RDM = int(RM % 100)
cm = int(RDM / 10)
RCM = int(RDM % 10)
print("")
print("Metros: " + str(m))
print("Decímetros: " + str(dm))
print("Centímetros: " + str(cm))
print("Milímetros: " + str(RCM))
