l = float(input("Ingrese el valor del lado: "))
a = float(input("Ingrese el valor del ancho: "))
P = float(l*2 + a*2)
A = float(l * a)
print("")
print("Perímetro: " + str(P))
print("Área: " + str(A))
